project:
  type: website
  output-dir: docs
  
  
website:
  title: "Human Gut Microbiome Metagenomics (Kilifi, 12-18 April 2026)"
  navbar:
    logo: "_extensions/img/WCS_Logo-Primary_Black.jpg"
    background: light
    left:
      - href: index.qmd
        text: Home
      - text: Modules
        menu:
          - href: course_modules_2026/module1/Module1_QC.qmd
            text: "Data Download, Quality Control and Decontamination"
          - href: course_modules_2026/module2/MAGs.qmd
            text: "Assembly and Metagenome-Assembled Genomes (MAGs)"
          - href: course_modules_2026/module3/module3.qmd
            text: "Building a Custom Microbiome Database"
          - href: course_modules_2026/module4/module4.qmd
            text: "Read-Based vs Assembly-Based Taxonomic Profiling"
          - href: course_modules_2026/module5/module5a_functional_profiling.qmd
            text: "Functional prediction and annotation from shotgun metagenomic data"
          - href: course_modules_2026/module6/module6.qmd
            text: "Building Phylogenetic Trees"

  
  page-navigation: true 
  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
  search:
    location: navbar
    type: textbox

output:
  html_document:
    highlight: pygments
    css: "_extensions/styles.css"
    toc: true
    toc_float:
      collapsed: false

format:
  html:
    number-sections: true
    number-depth: 5
    theme:
      #light: flatly

      light: [theme_lter-edu-light, _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss]
      dark: darkly
      #dark: [theme_lter-edu-dark, _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss]
    anchor-sections: true
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
