site_name: Human Gut Microbiome Metagenomics - Africa 2026
site_description: Documentation for My Project
theme:
  name: readthedocs
  navigation_depth: 4
  collapse_navigation: false
  titles_only: false

nav:
  - Course modules:
      - "Module 1: Data download, QC and decontamination":
          - Introduction: course_modules_2026/module1_qc/module1.md
          - MetaWRAP example: course_modules_2026/module1_qc/module1_metawrap.md
          - Results interpretation: course_modules_2026/module1_qc/module1_practical.md
      - "Module 2: Assembly and MAGs":
          - Introduction: course_modules_2026/module2_assembly/module2.md
          - MetaWRAP example: course_modules_2026/module2_assembly/module2_metawrap.md
          - Results interpretation: course_modules_2026/module2_assembly/module2_practical.md
      - "Module 3: Custom microbiome database":
          - Overview: course_modules_2026/module3_reference_databases/module3.md
      - "Module 4: Taxonomic profiling":
          - Overview: course_modules_2026/module4_profiling/module4.md 
      - "Module 5a: Functional annotation":
          - Functional profiling: course_modules_2026/module5_functional_annotation/module5a.md
          - Supplementary HUMAnN Nextflow: course_modules_2026/module5_functional_annotation/module5a_nextflow.md
      - "Module 5b: AMR and RGI":
          - Functional profiling: course_modules_2026/module5_functional_annotation/module5b.md
      - "Module 6: Phylogenetic trees":
          - Building phylogenetic trees: course_modules_2026/module6_phylogeny/module6.md